version: '2.1'

orbs:
  twitter-orb: jakousa/twitter-orb@1.0.1

jobs:
  log:
    docker:
      - image: cimg/base:latest
    resource_class: small
    steps:
      - run: echo << pipeline.git.branch >> << pipeline.git.tag >> 
  twitter:
    docker:
      - image: jakousa/twurl:latest
    resource_class: small
    steps:      
      - twitter-orb/tweet:
          access_secret: TOKEN_SECRET
          access_token: ACCESS_TOKEN
          consumer_key: API_KEY
          consumer_secret: API_SECRET
          contents: |
            (echo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME) has released << pipeline.git.tag >>:
            << pipeline.project.git_url >>/releases/tag/<< pipeline.git.tag >>

workflows:
  logging:
    jobs:
      - log  
  announcements:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - matches:
            pattern: ^v[0-9]+\.[0-9]+\.[0-9]+
            value: << pipeline.git.tag >> 
    jobs:
      - twitter:
          context: erica-twitter
