version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Sceptre/tweetrel-test/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: small
jobs:
  tag-release-announcement:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo "PR repo name: $CIRCLE_PR_REPONAME"
          echo "Tag: $CIRCLE_TAG"
          echo "URL: $CIRCLE_REPOSITORY_URL"
          echo "Task data: $CIRCLE_INTERNAL_TASK_DATA"
          echo "Project repo name: $CIRCLE_PROJECT_REPONAME"
          echo "Pipeline project url: << pipeline.project.git_url >>"


workflows:
  my-custom-workflow:
    jobs:
      - tag-release-announcement