version: '2.1'

orbs:
  twitter-orb: jakousa/twitter-orb@1.0.1

jobs:
  example-job:
    docker:
      - image: jakousa/twurl:latest
    resource_class: small
    steps:      
      - twitter-orb/tweet:
          contents: |
            (echo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME) has released << pipeline.git.tag >>:
            << pipeline.project.git_url >>/releases/tag/<< pipeline.git.tag >>

workflows:  
  pointers:
    jobs:
      - example-job:
          context: erica-twitter
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
