version: '2.1'

orbs:
  twitter-orb: jakousa/twitter-orb@1.0.1

jobs:
  twitter:
    docker:
      - image: jakousa/twurl:latest
    resource_class: small
    steps:      
      - twitter-orb/tweet:
          access_secret: TOKEN_SECRET
          access_token: ACCESS_TOKEN
          consumer_key: API_KEY
          consumer_secret: API_SECRET
          contents: |
            (echo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME) has released << pipeline.git.tag >>:
            << pipeline.project.git_url >>/releases/tag/<< pipeline.git.tag >>

workflows:  
  announcements:
    jobs:
      - twitter:
          context: erica-twitter
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
