version: '2.1'

orbs:
  twitter-orb: jakousa/twitter-orb@1.0.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: jakousa/twurl:latest
    resource_class: small
    environment:
      REPONAME: $CIRCLE_PROJECT_REPONAME
    steps:
      - twitter-orb/tweet:
          access_secret: TOKEN_SECRET
          access_token: ACCESS_TOKEN
          consumer_key: API_KEY
          consumer_secret: API_SECRET
          contents: |
            $REPONAME just released << pipeline.git.tag >>. Check it out!:
            << pipeline.project.git_url >>

workflows:
  example-workflow:
    jobs:
      - example-job