version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Sceptre/tweetrel-test/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    resource_class: small
    environment:
      REPO: $CIRCLE_PROJECT_REPONAME
      PAYLOAD: |
        tag_name: $CIRCLE_TAG
        html_url: << pipeline.project.git_url >>
        body: "Lots of exciting changes!"
jobs:
  tag-release-announcement:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          python pip install -Uqr .github/scripts/requirements.txt
          python .github/scripts/build-tweet.py

workflows:
  my-custom-workflow:
    jobs:
      - tag-release-announcement