version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Sceptre/tweetrel-test/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  tag-release-announcement:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          printenv

workflows:
  my-custom-workflow:
    jobs:
      - tag-release-announcement