version: '2.1'

orbs:
  twitter-orb: jakousa/twitter-orb@1.0.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: jakousa/twurl:latest
    resource_class: small
    environment:
      compiled_tweet: $CIRCLE_PROJECT_REPONAME
    steps:      
      - twitter-orb/tweet:
          access_secret: TOKEN_SECRET
          access_token: ACCESS_TOKEN
          consumer_key: API_KEY
          consumer_secret: API_SECRET
          contents: |
            echo $ACCESS_TOKEN
            (echo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME) has released << pipeline.git.tag >>:
            << pipeline.project.git_url >>

workflows:  
  pointers:
    jobs:
      - example-job:
          context: sceptreorg-twitter
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
