name: tweet
on:
  release:
    types: [published]
defaults:
  run: { shell: bash }

jobs:

  build:
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu] }
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Run script
      env:
        TWEETREL_TEMPLATE: |
          We are proud to announce the {tag_name} release of {repo}.
          
          For more, see: {html_url}. Here are the details:
          {body}
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_SECRETS: ${{ toJson(secrets) }}
      run: |
        pip install -Uq tweetrel
        python .github/scripts/build-tweet.py
